# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yagiz\Desktop\Workspace\Library_Assignment\Library_py\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import pyqtSignal, QObject
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

from utils.attributes import *
from utils.injection import *
from utils import temp
import Home

from PyQt5 import QtCore
from PyQt5 import QtGui
import sys

conn = temp.conn


class Login(QObject):

    def __init__(self):
        super().__init__()


    def setupUi(self, Widget):
        Widget.window().setWindowIcon(QIcon('assets/icon.jpg'))
        Widget.setMaximumSize(QtCore.QSize(500, 500))
        Widget.setObjectName("Widget")
        Widget.resize(500, 500)
        Widget.setStyleSheet("background-color: rgb(31, 33, 34);")
        self.frame = QtWidgets.QFrame(Widget)
        self.frame.setGeometry(QtCore.QRect(85, 114, 311, 251))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(39, 41, 42);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblAdministrator = QtWidgets.QLabel(self.frame)
        self.lblAdministrator.setGeometry(QtCore.QRect(50, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        self.lblAdministrator.setFont(font)
        self.lblAdministrator.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblAdministrator.setObjectName("lblAdministrator")
        self.lblLogin = QtWidgets.QLabel(self.frame)
        self.lblLogin.setGeometry(QtCore.QRect(190, 30, 60, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        self.lblLogin.setFont(font)
        self.lblLogin.setStyleSheet("color: rgb(156, 0, 0);")
        self.lblLogin.setObjectName("lblLogin")
        self.btnLogin = QtWidgets.QPushButton(self.frame)
        self.btnLogin.setGeometry(QtCore.QRect(110, 210, 71, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnLogin.setFont(font)
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogin.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "border: 1px solid;\n"
                                    "border-color:rgb(156, 0, 0);\n"
                                    "border-radius:10px;\n"
                                    "background-color:rgb(156, 0, 0);")
        self.btnLogin.setObjectName("btnLogin")
        self.txtUsername = QtWidgets.QLineEdit(self.frame)
        self.txtUsername.setGeometry(QtCore.QRect(50, 110, 191, 24))
        self.txtUsername.setStyleSheet("color: rgb(0, 0, 0);\n"
                                       "\n"
                                       "border: 1px solid;\n"
                                       "border-color:rgb(255, 255, 255);\n"
                                       "border-radius:25px;\n"
                                       "background-color:rgb(255, 255, 255);")
        self.txtUsername.setClearButtonEnabled(True)
        self.txtUsername.setObjectName("txtUsername")
        self.lblUsername = QtWidgets.QLabel(self.frame)
        self.lblUsername.setGeometry(QtCore.QRect(50, 90, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblUsername.setFont(font)
        self.lblUsername.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblUsername.setObjectName("lblUsername")
        self.txtPassword = QtWidgets.QLineEdit(self.frame)
        self.txtPassword.setGeometry(QtCore.QRect(50, 160, 191, 24))
        self.txtPassword.setStyleSheet("color: rgb(0, 0, 0);\n"
                                       "border: 1px solid;\n"
                                       "border-color:rgb(255, 255, 255);\n"
                                       "border-radius:55px;\n"
                                       "background-color:rgb(255, 255, 255);")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setClearButtonEnabled(True)
        self.txtPassword.setObjectName("txtPassword")
        self.lblPassword = QtWidgets.QLabel(self.frame)
        self.lblPassword.setGeometry(QtCore.QRect(50, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblPassword.setFont(font)
        self.lblPassword.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblPassword.setObjectName("lblPassword")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

        self.btnLogin.clicked.connect(lambda: self.login(Widget))

    def login(self,Widget):
        username = self.txtUsername.text()
        password = self.txtPassword.text()
        target = {'Username': username}
        data = Show.show_specified_record("administrator", target)

        if username != '' and password != '':
            data_password = None
            data_uid = None
            for row in data:
                data_password = str(row[7])
                data_uid = row[1]
            try:
                if data_password == password:
                    temp.temp_username = username
                    temp.temp_admin_uid = data_uid

                    self.window1 = QtWidgets.QWidget()
                    self.window1.hide()
                    self.window = QtWidgets.QMainWindow()
                    Home.Home().setupUi(self.window)
                    login_window = Login()
                    login_window.setupUi(self.window1)
                    self.window1.close()
                    self.window1.hide()
                    Widget.window().hide()
                    self.window.show()
                else:
                    Dialogs.error_dialog("Error", "An error has occurred.", "Username or Password doesn't match!")
            except Exception as e:
                Dialogs.error_dialog("Error", "An error has occurred.", str(e))
        else:
            Dialogs.error_dialog("Error", "An error has occurred.", "Please enter credentials")

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Login"))
        self.lblAdministrator.setText(_translate("Widget", "Administrator"))
        self.lblLogin.setText(_translate("Widget", "Login"))
        self.btnLogin.setText(_translate("Widget", "Login"))
        self.txtUsername.setPlaceholderText(_translate("Widget", "Username"))
        self.lblUsername.setText(_translate("Widget", "Username"))
        self.txtPassword.setPlaceholderText(_translate("Widget", "Password"))
        self.lblPassword.setText(_translate("Widget", "Password"))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Login()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
